const UserAction = {
  PENDING_SIGN_IN: "SIGN_IN",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "SIGN_IN_FAILED",

  PENDING_SIGN_UP: "SIGN_UP",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILED: "SIGN_UP_FAILED",

  PENDING_SIGN_OUT: "SIGN_OUT",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILED: "SIGN_OUT_FAILED",

  PENDING_GET_USER_INFO: "GET_USER_INFO",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED",

  CLEAN_USER_INFO: "CLEAR_USER_INFO",
};

const UserInputAction = {
  ON_CHANGE: "ON_CHANGE",
  ON_VALIDATE: "ON_VALIDATE",
};

const GeneralAction = {
  NETWORK_ERROR: "NETWORK_ERROR",
  NETWORK_OK: "NETWORK_OK",
};

export { UserAction, UserInputAction, GeneralAction };
